# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Bringgster < Formula
  desc ""
  homepage "https://github.com/bringg/bringgster"
  version "0.4.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bringg/bringgster/releases/download/v0.4.6/bringgster_0.4.6_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "2664d74f70918966fa1ec0bf7489a1d1faf267904b97e892a48325f0d5f8acf8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bringg/bringgster/releases/download/v0.4.6/bringgster_0.4.6_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8335d888d45bd38a04753435192ef385742da23baa6f740d65ae3536dbdd2645"
    end
  end

  def install
    bin.install "bringgster"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{bin}/bringgster</string>
      <string>minikube</string>
      <string>tunnel</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>UserName</key>
    <string>#{ENV["USER"]}</string>
  </dict>
</plist>

  EOS
  end
end
