# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Bringgster < Formula
  desc ""
  homepage "https://github.com/bringg/bringgster"
  version "0.2.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bringg/bringgster/releases/download/v0.2.9/bringgster_0.2.9_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "4d5f99d75fc949dcb652cc6f12b9d6593bcb247aa926a9c832d044db5084da6b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bringg/bringgster/releases/download/v0.2.9/bringgster_0.2.9_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c35106a209dd1e7aae198de0addc240e4abc242cbb5fc57b0fe4a956e5119e4d"
    end
  end

  def install
    bin.install "bringgster"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{bin}/bringgster</string>
      <string>minikube</string>
      <string>tunnel</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>UserName</key>
    <string>#{ENV["USER"]}</string>
  </dict>
</plist>

  EOS
  end
end
